import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import Navbar from './Navbar'
import '@radix-ui/themes/styles.css'
import {Theme} from '@radix-ui/themes'

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Theme>
        <Navbar />
        <main className='container mx-auto'>
        {children}
        </main>
        </Theme>
      </body>
    </html>
  )
}
